name: join_me
description: JoinMe is an application for sharing and manage your project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  auto_route: ^3.2.4
  bloc: ^8.0.3
  bloc_concurrency: ^0.2.0
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.12
  easy_localization: null
  equatable: ^2.0.3
  firebase_auth: ^3.3.14
  firebase_core: ^1.14.1
  firebase_messaging: ^11.4.1
  firebase_storage: ^10.2.17
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_login_facebook: ^1.5.0
  flutter_typeahead: ^3.2.5
  formz: ^0.4.1
  google_sign_in: ^5.3.1
  hive: ^2.2.2
  intl: ^0.17.0
  ionicons: ^0.1.2
  json_annotation: ^4.4.0
  keyboard_dismisser: ^2.0.1
  path_provider: ^2.0.11
  photo_manager: ^2.1.1
  photo_view: ^0.14.0
  smooth_page_indicator: ^1.0.0+2
  stream_transform: ^2.0.0
  table_calendar: ^3.0.5
  timeago: ^3.2.2

dev_dependencies:
  auto_route_generator: ^3.2.3
  bloc_test: ^9.0.3
  build_runner: ^2.1.10

  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.6
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/translations/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
